Front/#17/images view
MyUDC/MiUDC pull request #18
Opened 2024-06-25 16:30 UTC by LUISPINTO90

## ¿Qué se hizo?
- Se creó Testimony component
- Además de TestimonyImages component, donde se renderizan los layouts para
1.  Una sola imagen
2.  Dos imagenes
3.  Tres imagenes
- Creación de ImageView component, el cual es la vista que se despliega al abrir una imagen.

2024-06-26 04:59 UTC, LUISPINTO90 commented
## Capturas de pantallas:

- Vista de Testimony con 3 imagenes:
<img src="https://github.com/MyUDC/FRONT_MyUDC/assets/56972458/c5433ba2-9b86-4a43-8cea-e14398566ca7" width="300" height="auto">

- Vista de Testimony con 2 imagenes:
<img src="https://github.com/MyUDC/FRONT_MyUDC/assets/56972458/a17a2115-ef8f-48c6-a18d-a572448714da" width="300" height="auto">

- Vista de Testimony con 1 imagen:
<img src="https://github.com/MyUDC/FRONT_MyUDC/assets/56972458/f2015953-1afe-471d-b499-b9e1380d066d" width="300" height="auto">

- Vista de ImageView:
<img src="https://github.com/MyUDC/FRONT_MyUDC/assets/56972458/a7fbd6f3-d1e4-4880-befb-bd711408ddf2" width="800" height="auto">

2024-07-01 18:08 UTC, Branyoe requested changes

2024-07-08 07:05 UTC, LUISPINTO90 commented on src/components/ImageView/ImageView.tsx
Listo, ya quedó resuelto, quedo en espera de que aceptes el PR

2024-07-15 23:37 UTC, Branyoe commented on src/components/ImageView/ImageView.tsx
¡Confirmo!
Resultado: 
https://github.com/user-attachments/assets/4c7a0f39-a675-479d-a815-dc72fc78fb66

2024-07-15 23:39 UTC, Branyoe approved these changes

2024-07-15 23:39 UTC, merged