feat: add interests view
MyUDC/MiUDC pull request #33
Opened 2024-07-29 02:55 UTC by LUISPINTO90

## ¿Qué se hizo?
- Se creó el componente InterestCard
- Se creó la page de Interests
- Se añadió un archivo de prueba (data/interests.ts)

así luce:
<img src="https://github.com/user-attachments/assets/834f99a8-63c9-4a37-a6e8-3538c46b8f35" alt="image" width="250"/>

2024-07-30 03:16 UTC, Branyoe requested changes

2024-07-30 03:16 UTC, Branyoe commented on src/app/(without-auth)/interests/page.tsx
viejo esta vista requiere de auth, hay que moverla junto con todas sus dependencias a `/app/(with-auth)/user/interests`

2024-07-31 04:45 UTC, LUISPINTO90 commented on src/app/(without-auth)/interests/page.tsx
ya quedó movida viejo, con todo y autenticación.

<img src="https://github.com/user-attachments/assets/aa0d1279-888a-4d37-bbc2-76effcbf0348" alt="image" width="250"/>

2024-08-03 18:03 UTC, Branyoe commented on src/app/(without-auth)/interests/page.tsx
movida de tripas

2024-08-03 18:14 UTC, LUISPINTO90 commented on src/app/(without-auth)/interests/page.tsx
Ah viejo que pendejo, no la metí en user, la metí un directorio atrás

2024-08-03 18:31 UTC, Branyoe commented on src/app/(without-auth)/interests/page.tsx
papi te valio makina el layout de user.
ya lo agregué.

2024-08-03 18:33 UTC, LUISPINTO90 commented on src/app/(without-auth)/interests/page.tsx
Arre papito

2024-08-03 18:33 UTC, Branyoe commented on src/app/(without-auth)/interests/page.tsx
y la ruta era user/interests no /interests.
pero por lo demás buen trabajo viejo

2024-08-03 18:34 UTC, Branyoe approved these changes

2024-08-03 18:34 UTC, merged