Feat/#76/create post feature
MyUDC/MiUDC pull request #78
Opened 2024-09-16 22:35 UTC by LUISPINTO90

# Que se hizo?
Se desarrolló la funcionalidad de la creación de un post en la base de datos.

## Formulario de creación de Post
Se creó el componente y diseñó el componente NewPost, el cual es responsive (en mobil se ve como drawer y en pc como dialog), que muestra el formulario de creación de post.

### Implementaciones:
1. Cuenta con validaciones en el mínimo y máximo de del texto.
2. Validación de cantidad  de imágenes, y de tipos de formato de imagen

<img src="https://github.com/user-attachments/assets/223a904f-d803-4ea5-9d1b-80b8a6f0b228" width="250"/>

## POST del formulario
<img src="https://github.com/user-attachments/assets/b7a56757-d62d-4728-9f5a-ba86f4c5be94" width="250" />

### Implementaciones:
1. Al mandar el formulario te arroja un toast de éxito o de que falló el envío en algún caso.

Al refrescar la página se muestra el post
<img src="https://github.com/user-attachments/assets/450353ca-8956-4d38-babc-1b518d511bb0" width="250" />

2024-09-17 03:38 UTC, Branyoe requested changes

2024-09-17 03:38 UTC, Branyoe commented on src/app/api/career/[slug]/route.ts
esta ruta se puede evitar con un NotFound.tsx

2024-09-17 03:38 UTC, Branyoe commented on src/app/api/post/create/route.ts
En el back estoy manejando solo server actions, por eso ves muy pocas rutas definidas, hay algun motivo de peso para definirlo como ruta?

no digo que esté mal, pero si ya hay un estandar no hay que chilaquilear

2024-09-17 03:38 UTC, Branyoe commented on src/shared/components/PostForm/NewPost.tsx
> +    };
cambiar al patrón de server actions.

2024-09-17 03:38 UTC, Branyoe commented on src/shared/components/PostForm/PostForm.tsx
> +      const response = await fetch("/api/post/create", {
server action

2024-09-17 03:39 UTC, Branyoe commented
en general solo es adaptar bien el patrón de las serve action,
su principal beneficio es que te evitan las rutas

necesitas ayuda con eso?

2024-09-17 03:41 UTC, LUISPINTO90 commented
> en general solo es adaptar bien el patrón de las serve action, su principal beneficio es que te evitan las rutas
> 
> necesitas ayuda con eso?

Ahorita atiendo los cambios, e implemento las server actions viejillo. Si ocupo ayuda te digo.

2024-09-17 18:59 UTC, LUISPINTO90 commented
Ahora si, checa el PR. Brrrr.

2024-09-18 03:36 UTC, Branyoe approved these changes

2024-09-18 03:40 UTC, merged